src/gz immortalwrt_core https://downloads.immortalwrt.org/releases/23.05-SNAPSHOT/targets/ipq806x/generic/packages
src/gz immortalwrt_base https://downloads.immortalwrt.org/releases/23.05-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/base
src/gz immortalwrt_luci https://downloads.immortalwrt.org/releases/23.05-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/luci
src/gz immortalwrt_nss https://github.com/tongduychuong/immortalwrt/raw/openwrt-23.05/bin/targets/ipq806x/generic/packages
#src/gz immortalwrt_nss https://downloads.immortalwrt.org/releases/23.05-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/nss
src/gz immortalwrt_packages https://downloads.immortalwrt.org/releases/23.05-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/packages
src/gz immortalwrt_routing https://downloads.immortalwrt.org/releases/23.05-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/routing
#src/gz immortalwrt_sqm_scripts_nss https://downloads.immortalwrt.org/releases/23.05-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/sqm_scripts_nss
src/gz immortalwrt_telephony https://downloads.immortalwrt.org/releases/23.05-SNAPSHOT/packages/arm_cortex-a15_neon-vfpv4/telephony
